spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aitogether.cs@gmail.com
    password: wxntizicavipbysl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

front-server: http://localhost:3000
